spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/reliable-message?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

# dubbo配置
dubbo:
  application:
    name: rmq-service
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.cn.rmq.service.impl